### PR TITLE
Initial version - reboot and kexec

### PR DESCRIPTION
**Pull request by lzap**
Open for review.

### CODE REVIEW

**Comment by lzap** [comment]
This is my very first smart proxy plugin. It looks like I need to push LICENSE as well... will fix.

**Comment by lzap** [comment]
I will add tests later.

**Comment by lzap** [comment]
For myself: Remove legacy shell provider once this is merged: http://projects.theforeman.org/issues/11320

**Comment by lzap** [comment]
Need to find a way how to test this. Tried to install the gem via rubygems on the image, but it did not work out:

```
gem build smart_proxy_discovery_image.gemspec && sshpass -p redhat scp smart_proxy_discovery_image-1.0.0.gem root@192.168.122.68: && sshpass -p redhat ssh root@192.168.122.68 "gem install smart_proxy_discovery_image-1.0.0.gem && systemctl restart foreman-proxy && tail -f /tmp/proxy.log"
```

**Comment by stbenjam** [comment]
Merged as 7a2c95ac3fee1dfa2a914a76f7347dcd11a6596e, thanks @lzap!

**Comment by lzap** [comment]
Package pending: https://github.com/theforeman/foreman-packaging/pull/801

**Pull request closed without merging**
